### ISSUE TITLE
Can't run the basicbot on Windows to get Discord invitation link for basicbot

### ISSUE THREAD

**Issue by jonestone** [Habchy/BasicBot#4]
Hello Habchy. I was trying to upload the basicbot to our Discord channel , I followed all the steps from Habchy's github, but on the final step, when I need to start basicbot with my own bot security token and prefix, when I start it on my computer, it waits for 3-5 seconds with black window and then it writes somethig very quick, (I was trying to catch it with PrintScreen like hundreed times but I couldn't as it goes too fast) and closes that black window immediately.  So I stuck on trying to run it on my computer and the last step of inviting bot to Discord is impossible to perform, as due to setup instruction it should not write something very quick and then close, but give me a certain link for Bot Invitation to Discord.  Do you have an  idea what am I possibly doing wrong?

**Comment by PixelKitten** [comment]
```Python 3.7.0 (v3.7.0:1bf9cc5093) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PATHTOPYTHON\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\PATHTOPYTHON\Python\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\PATHTOPYTHON\Python\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\PATHTOPYTHON\Python\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```
Maybe a new syntax library with Python3.7.0 not updated in discord.py
"import" works well but the program stopped because of discord.py

**Comment by jonestone** [comment]
Thank you for your response. One woman already helped me and I managed finally to introduce basic bot to discord.

Thank you for your support.

**Comment by PixelKitten** [comment]
Then for those who search a solution for now, you just have to uninstall Python3.7.0 and download/install Python3.5.3
That will allow you to use Discord.py waiting for an update.

**Comment by Habchy** [comment]
Thanks for your help! 😄
